import { BadRequestException, ConflictException, ForbiddenException, Injectable, NotFoundException } from '@nestjs/common';
import { BillingCycle, LeaseBillingStatus, ProrationMethod } from '@prisma/client';
import { BillingRepository } from './billing.repository';
import { CreateLeaseBillingDto, GenerateRentScheduleDto, SecurityDepositDto, UpdateLeaseBillingDto } from './dto/billing.dto';

@Injectable()
export class BillingService {
  constructor(private readonly repository: BillingRepository) {}
  async create(actorUserId: string, organizationId: string, leaseId: string, input: CreateLeaseBillingDto) {
    await this.assertManager(actorUserId, organizationId); const lease = await this.getLease(organizationId, leaseId);
    this.validateCycle(input.billingCycle, input.customIntervalDays);
    if (lease.billingCalendar) throw new ConflictException('A billing calendar already exists for this lease');
    return this.repository.transaction(async (tx) => {
      const securityDeposit = input.securityDeposit ?? { requiredAmount: Number(lease.terms?.securityDeposit ?? 0) };
      const calendar = await tx.leaseBillingCalendar.create({ data: { leaseId, billingCycle: input.billingCycle, customIntervalDays: input.billingCycle === BillingCycle.CUSTOM ? input.customIntervalDays : null, dueDaysAfterPeriodStart: input.dueDaysAfterPeriodStart, prorationMethod: input.prorationMethod, status: input.status, currency: lease.terms?.currency ?? 'INR', escalationRules: input.escalationRules?.length ? { create: input.escalationRules.map((rule) => ({ effectiveAt: new Date(rule.effectiveAt), type: rule.type, amount: rule.amount, intervalMonths: rule.intervalMonths })) } : undefined, lateFeeRule: input.lateFeeRule ? { create: input.lateFeeRule } : undefined, securityDeposit: { create: this.depositData(securityDeposit) } }, include: { escalationRules: true, lateFeeRule: true, securityDeposit: true } });
      await this.repository.audit(actorUserId, organizationId, leaseId, 'lease.billing.created', { leaseId, calendarId: calendar.id }, tx); return calendar;
    });
  }
  async get(actorUserId: string, organizationId: string, leaseId: string) { await this.assertManager(actorUserId, organizationId); const calendar = await this.repository.findCalendar(organizationId, leaseId); if (!calendar) throw new NotFoundException('Lease billing calendar not found'); return calendar; }
  async update(actorUserId: string, organizationId: string, leaseId: string, input: UpdateLeaseBillingDto) { await this.assertManager(actorUserId, organizationId); const calendar = await this.getCalendar(organizationId, leaseId); return this.repository.transaction(async (tx) => { const updated = await tx.leaseBillingCalendar.update({ where: { id: calendar.id }, data: { status: input.status, dueDaysAfterPeriodStart: input.dueDaysAfterPeriodStart, prorationMethod: input.prorationMethod, lateFeeRule: input.lateFeeRule ? { upsert: { create: input.lateFeeRule, update: input.lateFeeRule } } : undefined }, include: { lateFeeRule: true, securityDeposit: true, escalationRules: true } }); await this.repository.audit(actorUserId, organizationId, leaseId, 'lease.billing.updated', { leaseId, calendarId: calendar.id }, tx); return updated; }); }
  async updateDeposit(actorUserId: string, organizationId: string, leaseId: string, input: SecurityDepositDto) { await this.assertManager(actorUserId, organizationId); const calendar = await this.getCalendar(organizationId, leaseId); const current = calendar.securityDeposit; const held = input.heldAmount ?? Number(current?.heldAmount ?? 0); const refunded = input.refundedAmount ?? Number(current?.refundedAmount ?? 0); if (refunded > held) throw new BadRequestException('Refunded amount cannot exceed held amount'); return this.repository.transaction(async (tx) => { const deposit = await tx.leaseSecurityDeposit.upsert({ where: { calendarId: calendar.id }, create: { calendarId: calendar.id, ...this.depositData(input) }, update: this.depositData(input) }); await this.repository.audit(actorUserId, organizationId, leaseId, 'lease.security_deposit.updated', { leaseId, calendarId: calendar.id }, tx); return deposit; }); }
  async schedules(actorUserId: string, organizationId: string, leaseId: string) { await this.assertManager(actorUserId, organizationId); const calendar = await this.getCalendar(organizationId, leaseId); return this.repository.listSchedules(calendar.id); }
  async generateSchedules(actorUserId: string, organizationId: string, leaseId: string, input: GenerateRentScheduleDto) {
    await this.assertManager(actorUserId, organizationId); const lease = await this.getLease(organizationId, leaseId); const calendar = lease.billingCalendar; if (!calendar) throw new NotFoundException('Lease billing calendar not found'); if (calendar.status === LeaseBillingStatus.ARCHIVED) throw new BadRequestException('Archived billing calendars cannot generate schedules');
    const throughAt = new Date(input.throughAt); if (Number.isNaN(throughAt.getTime()) || throughAt <= lease.startsAt) throw new BadRequestException('Generation date must be after the lease start date');
    const last = await this.repository.lastSchedule(calendar.id); const generated = this.buildSchedules(lease, calendar, last, throughAt);
    if (!generated.length) return [];
    return this.repository.transaction(async (tx) => { const schedules = []; for (const row of generated) schedules.push(await tx.leaseRentSchedule.create({ data: row })); await tx.leaseBillingCalendar.update({ where: { id: calendar.id }, data: { schedulesGeneratedThrough: schedules.at(-1)!.periodEndsAt } }); await this.repository.audit(actorUserId, organizationId, leaseId, 'lease.rent_schedule.generated', { leaseId, calendarId: calendar.id, count: schedules.length }, tx); return schedules; });
  }
  private buildSchedules(lease: any, calendar: any, last: any, throughAt: Date) {
    const rows: Array<any> = []; let start = last ? new Date(last.periodEndsAt) : new Date(lease.startsAt); let sequence = last ? last.sequence + 1 : 1; const finalAt = throughAt < lease.endsAt ? throughAt : lease.endsAt;
    while (start < finalAt) { const expectedEnd = this.nextPeriod(start, calendar.billingCycle, calendar.customIntervalDays); const end = expectedEnd < finalAt ? expectedEnd : finalAt; const fullDays = this.daysBetween(start, expectedEnd); const actualDays = this.daysBetween(start, end); const baseRent = Number(lease.terms?.rentAmount ?? 0); const proration = calendar.prorationMethod === ProrationMethod.DAILY && actualDays < fullDays ? baseRent - (baseRent * actualDays / fullDays) : 0; const escalation = this.escalationAmount(baseRent, calendar.escalationRules, start); rows.push({ calendarId: calendar.id, sequence: sequence++, periodStartsAt: start, periodEndsAt: end, dueAt: this.addDays(start, calendar.dueDaysAfterPeriodStart), rentAmount: baseRent, escalationAmount: escalation, prorationAmount: proration, totalDue: baseRent + escalation - proration }); start = end; }
    return rows;
  }
  private escalationAmount(base: number, rules: any[], date: Date) { return rules.filter((rule) => new Date(rule.effectiveAt) <= date).reduce((total, rule) => total + (rule.type === 'PERCENTAGE' ? base * Number(rule.amount) / 100 : Number(rule.amount)), 0); }
  private nextPeriod(date: Date, cycle: BillingCycle, customDays?: number | null) { const next = new Date(date); if (cycle === BillingCycle.WEEKLY) next.setUTCDate(next.getUTCDate() + 7); else if (cycle === BillingCycle.MONTHLY) next.setUTCMonth(next.getUTCMonth() + 1); else if (cycle === BillingCycle.QUARTERLY) next.setUTCMonth(next.getUTCMonth() + 3); else if (cycle === BillingCycle.HALF_YEARLY) next.setUTCMonth(next.getUTCMonth() + 6); else if (cycle === BillingCycle.YEARLY) next.setUTCFullYear(next.getUTCFullYear() + 1); else next.setUTCDate(next.getUTCDate() + (customDays ?? 0)); return next; }
  private addDays(date: Date, days: number) { const result = new Date(date); result.setUTCDate(result.getUTCDate() + days); return result; }
  private daysBetween(start: Date, end: Date) { return Math.max(1, Math.ceil((end.getTime() - start.getTime()) / 86_400_000)); }
  private validateCycle(cycle: BillingCycle, customDays?: number) { if (cycle === BillingCycle.CUSTOM && (!customDays || customDays < 1)) throw new BadRequestException('Custom billing requires a positive interval in days'); if (cycle !== BillingCycle.CUSTOM && customDays !== undefined) throw new BadRequestException('Custom interval days are only allowed for CUSTOM billing'); }
  private depositData(input: SecurityDepositDto) { const required = input.requiredAmount ?? 0; const held = input.heldAmount ?? 0; const refunded = input.refundedAmount ?? 0; if (refunded > held) throw new BadRequestException('Refunded amount cannot exceed held amount'); return { requiredAmount: required, heldAmount: held, refundedAmount: refunded, status: input.status ?? (required > 0 ? 'PENDING' : 'NOT_REQUIRED') }; }
  private async assertManager(userId: string, organizationId: string) { if (!(await this.repository.managerMembership(userId, organizationId))) throw new ForbiddenException('Lease billing permission is required'); }
  private async getLease(organizationId: string, leaseId: string) { const lease = await this.repository.findLease(organizationId, leaseId); if (!lease) throw new NotFoundException('Lease not found'); return lease; }
  private async getCalendar(organizationId: string, leaseId: string) { const calendar = await this.repository.findCalendar(organizationId, leaseId); if (!calendar) throw new NotFoundException('Lease billing calendar not found'); return calendar; }
}
