import { ConflictException, ForbiddenException, Injectable, NotFoundException, BadRequestException } from '@nestjs/common';
import { LeaseStatus, Prisma } from '@prisma/client';
import { CreateLeaseDocumentDto, CreateLeaseDto, LeasePartyDto, LeaseQueryDto, RenewLeaseDto, TerminateLeaseDto, UpdateLeaseDto } from './dto/lease.dto';
import { LeaseRepository } from './lease.repository';

@Injectable()
export class LeaseService {
  constructor(private readonly repository: LeaseRepository) {}
  async create(actorUserId: string, organizationId: string, input: CreateLeaseDto) {
    await this.assertManager(actorUserId, organizationId); this.assertDateRange(input.startsAt, input.endsAt);
    if (!(await this.repository.findActiveUnit(organizationId, input.unitId))) throw new NotFoundException('Unit not found');
    return this.repository.transaction(async (tx) => {
      const lease = await tx.lease.create({ data: { organizationId, unitId: input.unitId, code: input.code.trim().toUpperCase(), startsAt: new Date(input.startsAt), endsAt: new Date(input.endsAt), terms: { create: this.termsData(input.terms) }, parties: input.parties?.length ? { create: input.parties.map((party) => this.partyData(party)) } : undefined }, include: { terms: true, parties: true } });
      await this.repository.audit(actorUserId, organizationId, lease.id, 'lease.created', { leaseId: lease.id, unitId: input.unitId }, tx); return lease;
    });
  }
  async list(actorUserId: string, organizationId: string, query: LeaseQueryDto) {
    await this.assertManager(actorUserId, organizationId);
    const where: Prisma.LeaseWhereInput = { organizationId, deletedAt: null, ...(query.status ? { status: query.status } : {}), ...(query.unitId ? { unitId: query.unitId } : {}), ...(query.search ? { code: { contains: query.search.trim(), mode: 'insensitive' } } : {}) };
    const [items, total] = await Promise.all([this.repository.list(where, (query.page - 1) * query.limit, query.limit), this.repository.count(where)]);
    return { items, pagination: { page: query.page, limit: query.limit, total, totalPages: Math.ceil(total / query.limit) } };
  }
  async find(actorUserId: string, organizationId: string, leaseId: string) { await this.assertManager(actorUserId, organizationId); return this.get(organizationId, leaseId); }
  async update(actorUserId: string, organizationId: string, leaseId: string, input: UpdateLeaseDto) {
    await this.assertManager(actorUserId, organizationId); const lease = await this.get(organizationId, leaseId);
    if (input.status === LeaseStatus.ACTIVE && lease.status !== LeaseStatus.ACTIVE && await this.repository.activeLeaseForUnit(lease.unitId, leaseId)) throw new ConflictException('The unit already has an active lease');
    return this.repository.transaction(async (tx) => { const updated = await tx.lease.update({ where: { id: leaseId }, data: { status: input.status, terms: input.terms ? { upsert: { create: this.termsData(input.terms), update: this.termsData(input.terms) } } : undefined }, include: { terms: true } }); await this.repository.audit(actorUserId, organizationId, leaseId, 'lease.updated', { leaseId }, tx); return updated; });
  }
  async addParty(actorUserId: string, organizationId: string, leaseId: string, input: LeasePartyDto) { await this.assertManager(actorUserId, organizationId); await this.get(organizationId, leaseId); return this.repository.transaction(async (tx) => { const party = await tx.leaseParty.create({ data: { leaseId, ...this.partyData(input) } }); await this.repository.audit(actorUserId, organizationId, leaseId, 'lease.party.added', { leaseId, partyId: party.id }, tx); return party; }); }
  async addDocument(actorUserId: string, organizationId: string, leaseId: string, input: CreateLeaseDocumentDto) { await this.assertManager(actorUserId, organizationId); await this.get(organizationId, leaseId); return this.repository.transaction(async (tx) => { const document = await tx.leaseDocument.create({ data: { leaseId, type: input.type, name: input.name.trim(), storageKey: input.storageKey, mimeType: input.mimeType, sizeBytes: input.sizeBytes } }); await this.repository.audit(actorUserId, organizationId, leaseId, 'lease.document.added', { leaseId, documentId: document.id }, tx); return document; }); }
  async renew(actorUserId: string, organizationId: string, leaseId: string, input: RenewLeaseDto) { await this.assertManager(actorUserId, organizationId); const lease = await this.get(organizationId, leaseId); if (new Date(input.endsAt) <= lease.endsAt) throw new BadRequestException('Renewal end date must be after the current end date'); return this.repository.transaction(async (tx) => { const renewed = await tx.lease.update({ where: { id: leaseId }, data: { endsAt: new Date(input.endsAt), status: LeaseStatus.ACTIVE, renewals: { create: { previousEndsAt: lease.endsAt, renewedEndsAt: new Date(input.endsAt), rentAmount: input.rentAmount } }, terms: input.rentAmount !== undefined ? { update: { rentAmount: input.rentAmount } } : undefined }, include: { terms: true, renewals: { orderBy: { createdAt: 'desc' }, take: 1 } } }); await this.repository.audit(actorUserId, organizationId, leaseId, 'lease.renewed', { leaseId }, tx); return renewed; }); }
  async terminate(actorUserId: string, organizationId: string, leaseId: string, input: TerminateLeaseDto) { await this.assertManager(actorUserId, organizationId); await this.get(organizationId, leaseId); return this.repository.transaction(async (tx) => { const lease = await tx.lease.update({ where: { id: leaseId }, data: { status: LeaseStatus.NOTICE_TERMINATED, terminatedAt: input.terminatedAt ? new Date(input.terminatedAt) : new Date(), terminationReason: input.reason.trim() } }); await this.repository.audit(actorUserId, organizationId, leaseId, 'lease.termination.noticed', { leaseId }, tx); return lease; }); }
  async archive(actorUserId: string, organizationId: string, leaseId: string) { await this.assertManager(actorUserId, organizationId); await this.get(organizationId, leaseId); return this.repository.transaction(async (tx) => { const lease = await tx.lease.update({ where: { id: leaseId }, data: { status: LeaseStatus.ARCHIVED, deletedAt: new Date() } }); await this.repository.audit(actorUserId, organizationId, leaseId, 'lease.archived', { leaseId }, tx); return lease; }); }
  async restore(actorUserId: string, organizationId: string, leaseId: string) { await this.assertManager(actorUserId, organizationId); const lease = await this.repository.findLease(organizationId, leaseId, true); if (!lease) throw new NotFoundException('Lease not found'); return this.repository.transaction(async (tx) => { const restored = await tx.lease.update({ where: { id: leaseId }, data: { deletedAt: null, status: LeaseStatus.DRAFT } }); await this.repository.audit(actorUserId, organizationId, leaseId, 'lease.restored', { leaseId }, tx); return restored; }); }
  private async assertManager(userId: string, organizationId: string) { if (!(await this.repository.managerMembership(userId, organizationId))) throw new ForbiddenException('Lease management permission is required'); }
  private async get(organizationId: string, leaseId: string) { const lease = await this.repository.findLease(organizationId, leaseId); if (!lease) throw new NotFoundException('Lease not found'); return lease; }
  private assertDateRange(startsAt: string, endsAt: string) { if (new Date(startsAt) >= new Date(endsAt)) throw new BadRequestException('Lease end date must be after its start date'); }
  private termsData(input: CreateLeaseDto['terms']) { return { rentAmount: input.rentAmount, securityDeposit: input.securityDeposit, escalationRate: input.escalationRate, escalationMonths: input.escalationMonths, gracePeriodDays: input.gracePeriodDays, noticePeriodDays: input.noticePeriodDays, lateFeeAmount: input.lateFeeAmount, currency: input.currency?.trim().toUpperCase() }; }
  private partyData(input: LeasePartyDto) { return { role: input.role, name: input.name.trim(), email: input.email?.trim().toLowerCase(), mobile: input.mobile.trim() }; }
}
