import { ConflictException, Injectable, UnauthorizedException } from '@nestjs/common';
import { JwtService } from '@nestjs/jwt'; import * as argon2 from 'argon2'; import { Role } from '@prisma/client';
import { PrismaService } from '../common/prisma.service'; import { LoginDto, RegisterDto } from './dto';
@Injectable() export class AuthService {
  constructor(private prisma: PrismaService, private jwt: JwtService) {}
  async register(dto: RegisterDto) { const existing = await this.prisma.user.findFirst({ where: { email: dto.email } }); if (existing) throw new ConflictException('Email is already registered'); const passwordHash = await argon2.hash(dto.password); const tenant = await this.prisma.$transaction(async tx => { const tenant = await tx.tenant.create({ data: { name: dto.tenantName } }); const user = await tx.user.create({ data: { tenantId: tenant.id, email: dto.email.toLowerCase(), passwordHash, firstName: dto.firstName, lastName: dto.lastName, role: dto.role } }); return { tenant, user }; }); return this.issueTokens(tenant.user.id, tenant.tenant.id, tenant.user.role, tenant.user.email); }
  async login(dto: LoginDto) { const user = await this.prisma.user.findUnique({ where: { tenantId_email: { tenantId: dto.tenantId, email: dto.email.toLowerCase() } } }); if (!user || !user.isActive || !(await argon2.verify(user.passwordHash, dto.password))) throw new UnauthorizedException('Invalid credentials'); return this.issueTokens(user.id, user.tenantId, user.role, user.email); }
  async refresh(refreshToken: string) { const payload = await this.jwt.verifyAsync<{ sub: string; tenantId: string; role: Role; email: string }>(refreshToken, { secret: process.env.JWT_REFRESH_SECRET }); const user = await this.prisma.user.findUnique({ where: { id: payload.sub } }); if (!user?.refreshTokenHash || !(await argon2.verify(user.refreshTokenHash, refreshToken))) throw new UnauthorizedException('Refresh token is invalid'); return this.issueTokens(user.id, user.tenantId, user.role, user.email); }
  private async issueTokens(id: string, tenantId: string, role: Role, email: string) { const claims = { sub: id, tenantId, role, email }; const [accessToken, refreshToken] = await Promise.all([this.jwt.signAsync(claims, { secret: process.env.JWT_ACCESS_SECRET, expiresIn: '15m' }), this.jwt.signAsync(claims, { secret: process.env.JWT_REFRESH_SECRET, expiresIn: '30d' })]); await this.prisma.user.update({ where: { id }, data: { refreshTokenHash: await argon2.hash(refreshToken) } }); return { accessToken, refreshToken, tokenType: 'Bearer' }; }
}
