import { ForbiddenException, Injectable, NotFoundException } from '@nestjs/common';
import { Prisma, PropertyStatus } from '@prisma/client';
import { BulkImportUnitsDto, CreateAmenityDto, CreateBuildingDto, CreateFloorDto, CreatePropertyDocumentDto, CreatePropertyDto, CreatePropertyImageDto, CreateUnitDto, PropertyQueryDto, UnitQueryDto, UpdateBuildingDto, UpdateFloorDto, UpdateOccupancyDto, UpdatePropertyDto, UpdateUnitDto } from './dto/property.dto';
import { PropertyRepository } from './property.repository';

@Injectable()
export class PropertyService {
  constructor(private readonly repository: PropertyRepository) {}
  async create(actorUserId: string, organizationId: string, input: CreatePropertyDto) {
    await this.assertManager(actorUserId, organizationId);
    return this.repository.transaction(async (tx) => {
      const property = await tx.property.create({ data: { organizationId, ownerUserId: actorUserId, code: input.code.trim().toUpperCase(), name: input.name.trim(), description: input.description?.trim(), propertyType: input.propertyType, address: input.address ? { create: { ...input.address, line1: input.address.line1.trim(), city: input.address.city.trim(), country: input.address.country.trim().toUpperCase() } } : undefined, buildings: input.buildings ? { create: input.buildings.map((building, buildingIndex) => ({ code: building.code.trim().toUpperCase(), name: building.name.trim(), sortOrder: buildingIndex, floors: building.floors ? { create: building.floors.map((floor, floorIndex) => ({ number: floor.number, name: floor.name?.trim(), sortOrder: floorIndex, units: floor.units ? { create: floor.units.map((unit) => ({ code: unit.code.trim().toUpperCase(), name: unit.name?.trim(), unitType: unit.unitType?.trim(), status: unit.status, occupancyStatus: unit.occupancyStatus, bedrooms: unit.bedrooms, bathrooms: unit.bathrooms })) } : undefined })) } : undefined })) } : undefined, ownerships: { create: { userId: actorUserId, share: 100 } } }, include: { address: true, buildings: { include: { floors: { include: { units: true } } } } } });
      await this.repository.audit(actorUserId, organizationId, property.id, 'property.created', { propertyId: property.id }, tx);
      return property;
    });
  }
  async list(actorUserId: string, organizationId: string, query: PropertyQueryDto) {
    await this.assertManager(actorUserId, organizationId);
    const where: Prisma.PropertyWhereInput = { organizationId, deletedAt: null, ...(query.status ? { status: query.status } : {}), ...(query.search ? { OR: [{ name: { contains: query.search.trim(), mode: 'insensitive' } }, { code: { contains: query.search.trim(), mode: 'insensitive' } }] } : {}) };
    const [items, total] = await Promise.all([this.repository.list(where, (query.page - 1) * query.limit, query.limit, { [query.sortBy]: query.sortOrder }), this.repository.count(where)]);
    return { items, pagination: { page: query.page, limit: query.limit, total, totalPages: Math.ceil(total / query.limit) } };
  }
  async find(actorUserId: string, organizationId: string, propertyId: string) { await this.assertManager(actorUserId, organizationId); return this.get(propertyId, organizationId); }
  async update(actorUserId: string, organizationId: string, propertyId: string, input: UpdatePropertyDto) { await this.assertManager(actorUserId, organizationId); await this.get(propertyId, organizationId); return this.repository.transaction(async (tx) => { const property = await tx.property.update({ where: { id: propertyId }, data: { name: input.name?.trim(), description: input.description?.trim(), status: input.status, address: input.address ? { upsert: { create: { ...input.address, line1: input.address.line1.trim(), city: input.address.city.trim(), country: input.address.country.trim().toUpperCase() }, update: { ...input.address, line1: input.address.line1.trim(), city: input.address.city.trim(), country: input.address.country.trim().toUpperCase() } } } : undefined }, include: { address: true } }); await this.repository.audit(actorUserId, organizationId, propertyId, 'property.updated', { propertyId }, tx); return property; }); }
  async archive(actorUserId: string, organizationId: string, propertyId: string) { await this.assertManager(actorUserId, organizationId); await this.get(propertyId, organizationId); return this.repository.transaction(async (tx) => { const property = await tx.property.update({ where: { id: propertyId }, data: { deletedAt: new Date(), status: PropertyStatus.ARCHIVED } }); await this.repository.audit(actorUserId, organizationId, propertyId, 'property.archived', { propertyId }, tx); return property; }); }
  async restore(actorUserId: string, organizationId: string, propertyId: string) { await this.assertManager(actorUserId, organizationId); const found = await this.repository.findAny(propertyId, organizationId); if (!found) throw new NotFoundException('Property not found'); return this.repository.transaction(async (tx) => { const property = await tx.property.update({ where: { id: propertyId }, data: { deletedAt: null, status: PropertyStatus.DRAFT } }); await this.repository.audit(actorUserId, organizationId, propertyId, 'property.restored', { propertyId }, tx); return property; }); }
  async addAmenity(actorUserId: string, organizationId: string, propertyId: string, input: CreateAmenityDto) { await this.assertManager(actorUserId, organizationId); await this.get(propertyId, organizationId); return this.repository.transaction(async (tx) => { const amenity = await tx.propertyAmenity.create({ data: { propertyId, name: input.name.trim(), description: input.description?.trim() } }); await this.repository.audit(actorUserId, organizationId, propertyId, 'property.amenity.added', { propertyId, amenityId: amenity.id }, tx); return amenity; }); }
  async addImage(actorUserId: string, organizationId: string, propertyId: string, input: CreatePropertyImageDto) { await this.assertManager(actorUserId, organizationId); await this.get(propertyId, organizationId); return this.repository.transaction(async (tx) => { const image = await tx.propertyImage.create({ data: { propertyId, storageKey: input.storageKey, altText: input.altText } }); await this.repository.audit(actorUserId, organizationId, propertyId, 'property.image.added', { propertyId, imageId: image.id }, tx); return image; }); }
  async addDocument(actorUserId: string, organizationId: string, propertyId: string, input: CreatePropertyDocumentDto) { await this.assertManager(actorUserId, organizationId); await this.get(propertyId, organizationId); return this.repository.transaction(async (tx) => { const document = await tx.propertyDocument.create({ data: { propertyId, ...input } }); await this.repository.audit(actorUserId, organizationId, propertyId, 'property.document.added', { propertyId, documentId: document.id }, tx); return document; }); }
  async createBuilding(actor: string, org: string, propertyId: string, input: CreateBuildingDto) { await this.assertManager(actor, org); await this.get(propertyId, org); return this.repository.transaction(async (tx) => { const building = await tx.building.create({ data: { propertyId, code: input.code.trim().toUpperCase(), name: input.name.trim() } }); await this.repository.audit(actor, org, propertyId, 'property.building.created', { propertyId, buildingId: building.id }, tx); return building; }); }
  async updateBuilding(actor: string, org: string, propertyId: string, buildingId: string, input: UpdateBuildingDto) { await this.assertManager(actor, org); await this.getBuilding(propertyId, buildingId); return this.repository.transaction(async (tx) => { const building = await tx.building.update({ where: { id: buildingId }, data: { name: input.name?.trim() } }); await this.repository.audit(actor, org, propertyId, 'property.building.updated', { propertyId, buildingId }, tx); return building; }); }
  async archiveBuilding(actor: string, org: string, propertyId: string, buildingId: string, restore = false) { await this.assertManager(actor, org); await this.getBuilding(propertyId, buildingId, restore); return this.repository.transaction(async (tx) => { const building = await tx.building.update({ where: { id: buildingId }, data: { deletedAt: restore ? null : new Date() } }); await this.repository.audit(actor, org, propertyId, restore ? 'property.building.restored' : 'property.building.archived', { propertyId, buildingId }, tx); return building; }); }
  async createFloor(actor: string, org: string, propertyId: string, buildingId: string, input: CreateFloorDto) { await this.assertManager(actor, org); await this.getBuilding(propertyId, buildingId); return this.repository.transaction(async (tx) => { const floor = await tx.floor.create({ data: { buildingId, number: input.number, name: input.name?.trim() } }); await this.repository.audit(actor, org, propertyId, 'property.floor.created', { propertyId, buildingId, floorId: floor.id }, tx); return floor; }); }
  async updateFloor(actor: string, org: string, propertyId: string, buildingId: string, floorId: string, input: UpdateFloorDto) { await this.assertManager(actor, org); await this.getFloor(propertyId, buildingId, floorId); return this.repository.transaction(async (tx) => { const floor = await tx.floor.update({ where: { id: floorId }, data: { name: input.name?.trim() } }); await this.repository.audit(actor, org, propertyId, 'property.floor.updated', { propertyId, buildingId, floorId }, tx); return floor; }); }
  async archiveFloor(actor: string, org: string, propertyId: string, buildingId: string, floorId: string, restore = false) { await this.assertManager(actor, org); await this.getFloor(propertyId, buildingId, floorId, restore); return this.repository.transaction(async (tx) => { const floor = await tx.floor.update({ where: { id: floorId }, data: { deletedAt: restore ? null : new Date() } }); await this.repository.audit(actor, org, propertyId, restore ? 'property.floor.restored' : 'property.floor.archived', { propertyId, buildingId, floorId }, tx); return floor; }); }
  async createUnit(actor: string, org: string, propertyId: string, buildingId: string, floorId: string, input: CreateUnitDto) { await this.assertManager(actor, org); await this.getFloor(propertyId, buildingId, floorId); return this.repository.transaction(async (tx) => { const unit = await tx.unit.create({ data: { floorId, code: input.code.trim().toUpperCase(), name: input.name?.trim(), unitType: input.unitType?.trim(), status: input.status, occupancyStatus: input.occupancyStatus, bedrooms: input.bedrooms, bathrooms: input.bathrooms } }); await this.repository.audit(actor, org, propertyId, 'property.unit.created', { propertyId, buildingId, floorId, unitId: unit.id }, tx); return unit; }); }
  async bulkImportUnits(actor: string, org: string, propertyId: string, buildingId: string, floorId: string, input: BulkImportUnitsDto) { await this.assertManager(actor, org); await this.getFloor(propertyId, buildingId, floorId); return this.repository.transaction(async (tx) => { const units = await Promise.all(input.units.map((unit) => tx.unit.create({ data: { floorId, code: unit.code.trim().toUpperCase(), name: unit.name?.trim(), unitType: unit.unitType?.trim(), status: unit.status, occupancyStatus: unit.occupancyStatus, bedrooms: unit.bedrooms, bathrooms: unit.bathrooms } }))); await this.repository.audit(actor, org, propertyId, 'property.unit.bulk_imported', { propertyId, buildingId, floorId, count: units.length }, tx); return units; }); }
  async listUnits(actor: string, org: string, propertyId: string, query: UnitQueryDto) { await this.assertManager(actor, org); await this.get(propertyId, org); const where: Prisma.UnitWhereInput = { floor: { building: { propertyId, deletedAt: null }, deletedAt: null }, deletedAt: null, ...(query.status ? { status: query.status } : {}), ...(query.occupancyStatus ? { occupancyStatus: query.occupancyStatus } : {}), ...(query.search ? { OR: [{ code: { contains: query.search.trim(), mode: 'insensitive' } }, { name: { contains: query.search.trim(), mode: 'insensitive' } }] } : {}) }; const [items, total] = await Promise.all([this.repository.listUnits(where, (query.page - 1) * query.limit, query.limit), this.repository.countUnits(where)]); return { items, pagination: { page: query.page, limit: query.limit, total, totalPages: Math.ceil(total / query.limit) } }; }
  async updateUnit(actor: string, org: string, propertyId: string, buildingId: string, floorId: string, unitId: string, input: UpdateUnitDto) { await this.assertManager(actor, org); await this.getUnit(propertyId, buildingId, floorId, unitId); return this.repository.transaction(async (tx) => { const unit = await tx.unit.update({ where: { id: unitId }, data: { name: input.name?.trim(), unitType: input.unitType?.trim(), status: input.status } }); await this.repository.audit(actor, org, propertyId, 'property.unit.updated', { propertyId, unitId }, tx); return unit; }); }
  async updateOccupancy(actor: string, org: string, propertyId: string, buildingId: string, floorId: string, unitId: string, input: UpdateOccupancyDto) { await this.assertManager(actor, org); await this.getUnit(propertyId, buildingId, floorId, unitId); return this.repository.transaction(async (tx) => { await tx.unitOccupancy.updateMany({ where: { unitId, endsAt: null }, data: { endsAt: new Date() } }); const unit = await tx.unit.update({ where: { id: unitId }, data: { occupancyStatus: input.status } }); await tx.unitOccupancy.create({ data: { unitId, status: input.status, occupantName: input.status === 'OCCUPIED' ? input.occupantName?.trim() : null, occupantEmail: input.status === 'OCCUPIED' ? input.occupantEmail?.trim().toLowerCase() : null } }); await this.repository.audit(actor, org, propertyId, 'property.unit.occupancy.updated', { propertyId, unitId, status: input.status }, tx); return unit; }); }
  async archiveUnit(actor: string, org: string, propertyId: string, buildingId: string, floorId: string, unitId: string, restore = false) { await this.assertManager(actor, org); await this.getUnit(propertyId, buildingId, floorId, unitId, restore); return this.repository.transaction(async (tx) => { const unit = await tx.unit.update({ where: { id: unitId }, data: { deletedAt: restore ? null : new Date(), status: restore ? 'ACTIVE' : 'ARCHIVED' } }); await this.repository.audit(actor, org, propertyId, restore ? 'property.unit.restored' : 'property.unit.archived', { propertyId, unitId }, tx); return unit; }); }
  private async assertManager(userId: string, organizationId: string) { if (!(await this.repository.managerMembership(userId, organizationId))) throw new ForbiddenException('Property management permission is required'); }
  private async get(propertyId: string, organizationId: string) { const property = await this.repository.findActive(propertyId, organizationId); if (!property) throw new NotFoundException('Property not found'); return property; }
  private async getBuilding(propertyId: string, buildingId: string, includeDeleted = false) { const building = await this.repository.findBuilding(propertyId, buildingId, includeDeleted); if (!building) throw new NotFoundException('Building not found'); return building; }
  private async getFloor(propertyId: string, buildingId: string, floorId: string, includeDeleted = false) { const floor = await this.repository.findFloor(propertyId, buildingId, floorId, includeDeleted); if (!floor) throw new NotFoundException('Floor not found'); return floor; }
  private async getUnit(propertyId: string, buildingId: string, floorId: string, unitId: string, includeDeleted = false) { const unit = await this.repository.findUnit(propertyId, buildingId, floorId, unitId, includeDeleted); if (!unit) throw new NotFoundException('Unit not found'); return unit; }
}
