import { Type } from 'class-transformer';
import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';
import { IsArray, IsEnum, IsInt, IsNotEmpty, IsOptional, IsString, Max, MaxLength, Min, ValidateNested } from 'class-validator';
import { OccupancyStatus, PropertyDocumentType, PropertyStatus, PropertyType, UnitStatus } from '@prisma/client';

class AddressDto { @ApiProperty() @IsString() @IsNotEmpty() @MaxLength(200) line1!: string; @ApiPropertyOptional() @IsOptional() @IsString() @MaxLength(200) line2?: string; @ApiProperty() @IsString() @MaxLength(100) city!: string; @ApiProperty() @IsString() @MaxLength(2) country!: string; @ApiPropertyOptional() @IsOptional() @IsString() @MaxLength(100) state?: string; @ApiPropertyOptional() @IsOptional() @IsString() @MaxLength(20) postalCode?: string; }
class UnitDto { @ApiProperty() @IsString() @MaxLength(50) code!: string; @ApiPropertyOptional() @IsOptional() @IsString() @MaxLength(100) name?: string; @ApiPropertyOptional() @IsOptional() @IsString() @MaxLength(50) unitType?: string; @ApiPropertyOptional({ enum: UnitStatus }) @IsOptional() @IsEnum(UnitStatus) status?: UnitStatus; @ApiPropertyOptional({ enum: OccupancyStatus }) @IsOptional() @IsEnum(OccupancyStatus) occupancyStatus?: OccupancyStatus; @ApiPropertyOptional() @IsOptional() @IsInt() @Min(0) @Max(100) bedrooms?: number; @ApiPropertyOptional() @IsOptional() @IsInt() @Min(0) @Max(100) bathrooms?: number; }
class FloorDto { @ApiProperty() @IsInt() @Min(-20) @Max(500) number!: number; @ApiPropertyOptional() @IsOptional() @IsString() @MaxLength(100) name?: string; @ApiPropertyOptional({ type: [UnitDto] }) @IsOptional() @IsArray() @ValidateNested({ each: true }) @Type(() => UnitDto) units?: UnitDto[]; }
class BuildingDto { @ApiProperty() @IsString() @MaxLength(50) code!: string; @ApiProperty() @IsString() @MaxLength(150) name!: string; @ApiPropertyOptional({ type: [FloorDto] }) @IsOptional() @IsArray() @ValidateNested({ each: true }) @Type(() => FloorDto) floors?: FloorDto[]; }

export class CreatePropertyDto {
  @ApiProperty() @IsString() @MaxLength(50) code!: string;
  @ApiProperty() @IsString() @IsNotEmpty() @MaxLength(200) name!: string;
  @ApiProperty({ enum: PropertyType }) @IsEnum(PropertyType) propertyType!: PropertyType;
  @ApiPropertyOptional() @IsOptional() @IsString() @MaxLength(5000) description?: string;
  @ApiPropertyOptional({ type: AddressDto }) @IsOptional() @ValidateNested() @Type(() => AddressDto) address?: AddressDto;
  @ApiPropertyOptional({ type: [BuildingDto] }) @IsOptional() @IsArray() @ValidateNested({ each: true }) @Type(() => BuildingDto) buildings?: BuildingDto[];
}
export class UpdatePropertyDto { @ApiPropertyOptional() @IsOptional() @IsString() @MaxLength(200) name?: string; @ApiPropertyOptional() @IsOptional() @IsString() @MaxLength(5000) description?: string; @ApiPropertyOptional({ enum: PropertyStatus }) @IsOptional() @IsEnum(PropertyStatus) status?: PropertyStatus; @ApiPropertyOptional({ type: AddressDto }) @IsOptional() @ValidateNested() @Type(() => AddressDto) address?: AddressDto; }
export class PropertyQueryDto { @ApiPropertyOptional() @IsOptional() @IsString() @MaxLength(200) search?: string; @ApiPropertyOptional({ enum: PropertyStatus }) @IsOptional() @IsEnum(PropertyStatus) status?: PropertyStatus; @ApiPropertyOptional() @IsOptional() @Type(() => Number) @IsInt() @Min(1) page = 1; @ApiPropertyOptional() @IsOptional() @Type(() => Number) @IsInt() @Min(1) @Max(100) limit = 20; @ApiPropertyOptional({ enum: ['name', 'createdAt'] }) @IsOptional() @IsEnum(['name', 'createdAt']) sortBy: 'name' | 'createdAt' = 'createdAt'; @ApiPropertyOptional({ enum: ['asc', 'desc'] }) @IsOptional() @IsEnum(['asc', 'desc']) sortOrder: 'asc' | 'desc' = 'desc'; }
export class CreateAmenityDto { @ApiProperty() @IsString() @IsNotEmpty() @MaxLength(100) name!: string; @ApiPropertyOptional() @IsOptional() @IsString() @MaxLength(500) description?: string; }
export class CreatePropertyImageDto { @ApiProperty() @IsString() @MaxLength(1024) storageKey!: string; @ApiPropertyOptional() @IsOptional() @IsString() @MaxLength(250) altText?: string; }
export class CreatePropertyDocumentDto { @ApiProperty({ enum: PropertyDocumentType }) @IsEnum(PropertyDocumentType) type!: PropertyDocumentType; @ApiProperty() @IsString() @MaxLength(250) name!: string; @ApiProperty() @IsString() @MaxLength(1024) storageKey!: string; @ApiProperty() @IsString() @MaxLength(100) mimeType!: string; @ApiProperty() @IsInt() @Min(0) sizeBytes!: number; }
export class CreateBuildingDto { @ApiProperty() @IsString() @MaxLength(50) code!: string; @ApiProperty() @IsString() @MaxLength(150) name!: string; }
export class UpdateBuildingDto { @ApiPropertyOptional() @IsOptional() @IsString() @MaxLength(150) name?: string; }
export class CreateFloorDto { @ApiProperty() @IsInt() @Min(-20) @Max(500) number!: number; @ApiPropertyOptional() @IsOptional() @IsString() @MaxLength(100) name?: string; }
export class UpdateFloorDto { @ApiPropertyOptional() @IsOptional() @IsString() @MaxLength(100) name?: string; }
export class CreateUnitDto { @ApiProperty() @IsString() @MaxLength(50) code!: string; @ApiPropertyOptional() @IsOptional() @IsString() @MaxLength(100) name?: string; @ApiPropertyOptional() @IsOptional() @IsString() @MaxLength(50) unitType?: string; @ApiPropertyOptional({ enum: UnitStatus }) @IsOptional() @IsEnum(UnitStatus) status?: UnitStatus; @ApiPropertyOptional({ enum: OccupancyStatus }) @IsOptional() @IsEnum(OccupancyStatus) occupancyStatus?: OccupancyStatus; @ApiPropertyOptional() @IsOptional() @IsInt() @Min(0) @Max(100) bedrooms?: number; @ApiPropertyOptional() @IsOptional() @IsInt() @Min(0) @Max(100) bathrooms?: number; }
export class UpdateUnitDto { @ApiPropertyOptional() @IsOptional() @IsString() @MaxLength(100) name?: string; @ApiPropertyOptional({ enum: UnitStatus }) @IsOptional() @IsEnum(UnitStatus) status?: UnitStatus; @ApiPropertyOptional() @IsOptional() @IsString() @MaxLength(50) unitType?: string; }
export class UpdateOccupancyDto { @ApiProperty({ enum: OccupancyStatus }) @IsEnum(OccupancyStatus) status!: OccupancyStatus; @ApiPropertyOptional() @IsOptional() @IsString() @MaxLength(200) occupantName?: string; @ApiPropertyOptional() @IsOptional() @IsString() @MaxLength(320) occupantEmail?: string; }
export class UnitQueryDto { @ApiPropertyOptional() @IsOptional() @IsString() @MaxLength(100) search?: string; @ApiPropertyOptional({ enum: UnitStatus }) @IsOptional() @IsEnum(UnitStatus) status?: UnitStatus; @ApiPropertyOptional({ enum: OccupancyStatus }) @IsOptional() @IsEnum(OccupancyStatus) occupancyStatus?: OccupancyStatus; @ApiPropertyOptional() @IsOptional() @Type(() => Number) @IsInt() @Min(1) page = 1; @ApiPropertyOptional() @IsOptional() @Type(() => Number) @IsInt() @Min(1) @Max(100) limit = 20; }
export class BulkImportUnitsDto { @ApiProperty({ type: [CreateUnitDto] }) @IsArray() @ValidateNested({ each: true }) @Type(() => CreateUnitDto) units!: CreateUnitDto[]; }
